name: build_kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: set up environment
        run: |
          sudo apt update -y
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev unzip zipalign
          
      - name: build kernel
        run: |
          chmod +x build_tool.sh
          ./build_tool.sh
          
      - name: upload 
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: kernel
          path: ${{ github.workspace }}/Image.gz-dtb
