name: build_kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: set up environment
        run: |
          sudo apt update -y
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick libncurses5-dev libssl-dev libxml2 libxml2-utils lzop rsync schedtool squashfs-tools xsltproc zip zlib1g-dev unzip
          sudo apt install -y python2
          sudo ln -sf /usr/bin/python2 /usr/bin/python
          
      - name: pull compiler
        run: |
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b master gcc
          
      - name: build kernel
        run: |
          chmod +x build_tool.sh
          ./build_tool.sh
          
      - name: upload 
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: kernel
          path: ${{ github.workspace }}/Image.gz-dtb
